### ISSUE TITLE
Bottom enclosure thickness

### ISSUE THREAD

**Issue by jimt** [ale1800/ESP-360-REMOTE#1]
When I tried to have JLPCB 3D print the enclosure in 9000R resin, they complained that the bottom piece wall thickness was too thin.  They suggested it be at least 0.8mm, or even better 1.5mm.

![bottom](https://user-images.githubusercontent.com/180326/228126786-ed991c86-d529-4873-bc87-e8dc11a7f9b2.png)

commit:  dfe3e82

**Comment by ale1800** [comment]
Hello! They told me the same, but make them print it
anyway, It will work👍
