### ISSUE TITLE
Do not hardcode locations into configuration YAML

### ISSUE THREAD

**Issue by askpatrickw** [ale1800/ESP-360-REMOTE#3]
In the configuration YAMLs, the "Living Room" location is hardcoded into the files. Location is usually part of the home automation configuration. Sensor 1 is in RoomA. Identical Sensor 2 is in RoomB.

Happy to submit a PR if that makes sense to you.

**Comment by ale1800** [comment]
Hello! Yeah, you are totally right! My fault. Please submit the PR, thanks!
