### ISSUE TITLE
Print Setting?

### ISSUE THREAD

**Issue by LostInIgnorance** [ale1800/ESP-360-REMOTE#8]
Can you add the print settings you are using to the STL file folder please

**Comment by ale1800** [comment]
Hello, sorry for my late response. I don't know if you still need it. However what I use for the bottom part is:

No support
Infill: 20%
Line Width: 0.44 mm
Layer height: 0.2 mm

For the top part you can add supports for the highest point of the dome

If you need some particular parameter, please ask me

**Comment by LostInIgnorance** [comment]
@ale1800 Thank you for that information as I always seem to be having issues with the locator pins on the bottom and having these settings should help.

The other question I have is what program was used to create the base/top as I would like to modify the original to allow wall mounting from the base, but I think I need the original files. Also, could you share the originals?

**Comment by ale1800** [comment]
@LostInIgnorance I used shapr3d to design the enclosure. I can share the step files or even the "native" ones if you use the same program

**Comment by ale1800** [comment]
@LostInIgnorance I uploaded [here](https://github.com/ale1800/ESP-360-REMOTE/tree/main/Enclosure/Original%20files) everything

**Comment by LostInIgnorance** [comment]
@ale1800 I don't have shapr3d and I am not sure how to modify the same base, but with a wall mount option (just a couple of screw holes on a bracket/extended wall). The USB C cord I am using is below so I don't need much space in the back for the USB C connection.

https://www.amazon.com/gp/product/B0CCJRWKC5
