### ISSUE TITLE
IR Receiver events

### ISSUE THREAD

**Issue by Haves1001** [ale1800/ESP-360-REMOTE#9]
Hi, I would like to primarily use the device for receiving signals from my IR remote control.
I've been reading in the documentation that "The same feature will soon be available for the infrared receiver as well." - now my question, is that feature already available for IR events?

**Comment by ale1800** [comment]
Hello! Sure, it will work. If you missed it, have a look here: https://www.crowdsupply.com/aaelectronics/esp-360-remote/updates/a-deep-dive-into-automation
